"""Random scenario quiz: play a frozen mid-game position, then compare
your choices against what each AI would do.

Scenarios are generated by letting two AIs play a real hand for a random
number of turns and freezing it at your seat's draw phase - so the
position has a genuine discard history and opponent-tracking data for
the context-aware AIs to reason from.

Usage:
    uv run gin-scenario                 # 3 scenarios, random seed
    uv run gin-scenario --count 5 --seed 42
    uv run gin-scenario --mc-sims 1000  # stronger (slower) MC advice
"""

from __future__ import annotations

import argparse
import random
import sys
from dataclasses import dataclass, replace

from gin_rummy.ai import BasicAI, ContextAwareAI, MonteCarloAI, DrawChoice
from gin_rummy.cli import display_hand_by_suit
from gin_rummy.config import get_config
from gin_rummy.game import Game, GamePhase
from gin_rummy.game_runner import (
    calculate_post_discard_deadwood,
    execute_ai_turn,
)
from gin_rummy.models import Card, Hand

HUMAN_SEAT = 0
MAX_GENERATION_ATTEMPTS = 50


@dataclass
class PanelMember:
    """One AI whose choices are compared against the player's."""

    name: str
    ai: BasicAI
    draw_agreements: int = 0
    discard_agreements: int = 0
    knock_agreements: int = 0

    @property
    def is_context_aware(self) -> bool:
        return isinstance(self.ai, ContextAwareAI)


class _PanelFeedCallbacks:
    """Turn callbacks that feed opponent actions to the panel AIs.

    The panel advises HUMAN_SEAT, so it observes the other player.
    """

    def __init__(self, panel: list[PanelMember], opponent_name: str) -> None:
        self.panel = panel
        self.opponent_name = opponent_name

    def _context_members(self):
        return [m.ai for m in self.panel if m.is_context_aware]

    def on_draw(self, player, source, card) -> None:
        if player.name == self.opponent_name and source == DrawChoice.DISCARD:
            for ai in self._context_members():
                ai.record_opponent_pickup(card)

    def on_discard(self, player, card) -> None:
        if player.name == self.opponent_name:
            for ai in self._context_members():
                ai.record_opponent_discard(card)

    def on_knock(self, player, discard, deadwood, result) -> None:
        pass

    def on_turn_complete(self, player, actions) -> None:
        pass


def build_panel(mc_sims: int, mc_workers: int) -> list[PanelMember]:
    """Create the advisor AIs (fresh instances per scenario)."""
    cfg = get_config()
    mc_cfg = replace(
        cfg.monte_carlo_ai,
        draw_simulations=mc_sims,
        discard_simulations=mc_sims,
        knock_simulations=mc_sims,
        max_workers=mc_workers,
    )
    mc_config = replace(cfg, monte_carlo_ai=mc_cfg)
    return [
        PanelMember("BasicAI", BasicAI()),
        PanelMember("ContextAwareAI", ContextAwareAI()),
        PanelMember("MonteCarloAI", MonteCarloAI(mc_config)),
    ]


def generate_scenario(
    seed: int,
    panel: list[PanelMember],
    min_turns: int = 4,
    max_turns: int = 14,
) -> Game | None:
    """Play a real hand between two AIs and freeze it at the human seat.

    Returns a Game in DRAWING phase with current player == HUMAN_SEAT,
    or None if this seed's hand ended before reaching the target turn.
    """
    random.seed(seed)
    target_turns = random.randint(min_turns, max_turns)

    game = Game("You", "Opponent")
    game.deal()

    # AIs that actually play out the position (independent of the panel)
    seat_ais = {0: ContextAwareAI(), 1: ContextAwareAI()}
    callbacks = _PanelFeedCallbacks(panel, opponent_name="Opponent")

    # Opening discard by the non-dealer
    opener_idx = game.current_player_idx
    opener = seat_ais[opener_idx]
    discard = opener.decide_discard(game.current_player.hand)
    game.discard_to_start(discard)
    if opener_idx != HUMAN_SEAT:
        callbacks.on_discard(game.players[opener_idx], discard)

    turns_played = 0
    while turns_played < target_turns or game.current_player_idx != HUMAN_SEAT:
        if game.phase != GamePhase.DRAWING:
            return None  # hand ended early (knock)

        actor_idx = game.current_player_idx
        actor = seat_ais[actor_idx]
        other = seat_ais[1 - actor_idx]

        result, actions, round_result = execute_ai_turn(
            game, actor, other_ai=other,
            callbacks=callbacks if actor_idx != HUMAN_SEAT else None,
        )
        if result.name != "CONTINUE":
            return None  # knock or deck exhaustion - unusable scenario

        turns_played += 1
        if turns_played > max_turns * 3:
            return None

    if game.phase != GamePhase.DRAWING or game.current_player_idx != HUMAN_SEAT:
        return None
    return game


def show_position(game: Game) -> None:
    """Print the frozen position from the human's perspective."""
    ctx = game.get_game_context(HUMAN_SEAT)
    human = game.players[HUMAN_SEAT]
    analysis = human.hand.analyze()

    print("\n" + "=" * 62)
    print("SCENARIO")
    print("=" * 62)
    print("\nYour hand:")
    display_hand_by_suit(human.hand, show_numbers=False)
    if analysis.melds:
        print("Melds:    " + " | ".join(str(m) for m in analysis.melds))
    print(f"\nDiscard top:   {game.top_of_discard}")
    print(f"Deck remaining: {len(game.deck)}")

    pickups = ctx.opponent_pickups
    if pickups:
        print(f"Opponent picked up: {' '.join(str(c) for c in pickups)}")
    buried = sorted(ctx.dead_cards)
    if buried:
        print(f"Buried discards:    {' '.join(str(c) for c in buried)}")


def ask(prompt: str, valid: set[str]) -> str:
    while True:
        answer = input(prompt).strip().lower()
        if answer == "q":
            print("\nQuiz ended.")
            sys.exit(0)
        if answer in valid:
            return answer
        print(f"Please enter one of: {', '.join(sorted(valid))} (or q to quit)")


def ask_draw(game: Game) -> DrawChoice:
    answer = ask(
        f"\nDraw from [d]eck or take {game.top_of_discard} from [p]ile? ",
        {"d", "p"},
    )
    return DrawChoice.DISCARD if answer == "p" else DrawChoice.DECK


def ask_discard(game: Game) -> Card:
    print("\nYour hand after drawing:")
    cards = display_hand_by_suit(game.players[HUMAN_SEAT].hand, show_numbers=True)
    while True:
        answer = input("\nCard # to discard: ").strip().lower()
        if answer == "q":
            print("\nQuiz ended.")
            sys.exit(0)
        try:
            idx = int(answer)
            if 1 <= idx <= len(cards):
                card = cards[idx - 1]
                if card == game.discard_blocked_card:
                    print(f"You can't discard {card} - you just took it from the pile.")
                    continue
                return card
        except ValueError:
            pass
        print(f"Enter a number 1-{len(cards)}")


def panel_draw_choices(panel: list[PanelMember], game: Game) -> list[dict]:
    """Ask each panel AI for its draw choice on the current position.

    Returns one dict per AI: {name, choice (DrawChoice), reasoning}.
    """
    hand = game.players[HUMAN_SEAT].hand
    ctx = game.get_game_context(HUMAN_SEAT)
    choices = []
    for member in panel:
        if member.is_context_aware:
            member.ai.update_context(ctx)
            reasoning = member.ai.decide_draw_with_reasoning(
                hand, game.top_of_discard, ctx
            )
        else:
            reasoning = member.ai.decide_draw_with_reasoning(hand, game.top_of_discard)
        choices.append({
            "name": member.name,
            "choice": reasoning.choice,
            "reasoning": reasoning.reasoning,
        })
    return choices


def panel_discard_choices(panel: list[PanelMember], game: Game) -> list[dict]:
    """Ask each panel AI for its discard on the current 11-card hand.

    Returns one dict per AI: {name, card (Card), reasoning, mc_candidates}.
    mc_candidates is MC's EV list (or None for other AIs).
    """
    hand = game.players[HUMAN_SEAT].hand
    ctx = game.get_game_context(HUMAN_SEAT)
    choices = []
    for member in panel:
        if member.is_context_aware:
            member.ai.update_context(ctx)
        reasoning = member.ai.decide_discard_with_reasoning(hand)
        mc_candidates = None
        if isinstance(member.ai, MonteCarloAI) and member.ai.last_mc_thinking:
            thinking = member.ai.last_mc_thinking.get("discard")
            if thinking:
                mc_candidates = thinking["candidates"]
        choices.append({
            "name": member.name,
            "card": reasoning.card,
            "reasoning": reasoning.reasoning,
            "mc_candidates": mc_candidates,
        })
    return choices


def panel_knock_choices(
    panel: list[PanelMember], game: Game, post_hand: Hand, pending: Card
) -> list[dict]:
    """Ask each panel AI whether it would knock with the post-discard hand.

    Returns one dict per AI: {name, knocks (bool), reasoning}.
    """
    ctx = game.get_game_context(HUMAN_SEAT)
    choices = []
    for member in panel:
        if member.is_context_aware:
            member.ai.update_context(ctx)
            reasoning = member.ai.should_knock_with_reasoning(
                post_hand, ctx, pending_discard=pending
            )
        else:
            reasoning = member.ai.should_knock_with_reasoning(post_hand)
        choices.append({
            "name": member.name,
            "knocks": reasoning.should_knock,
            "reasoning": reasoning.reasoning,
        })
    return choices


def reveal_draw_choices(
    panel: list[PanelMember], game: Game, user_choice: DrawChoice
) -> None:
    took = f"take {game.top_of_discard}" if user_choice == DrawChoice.DISCARD else "draw from deck"
    print(f"\nYou chose: {took}")
    print("-" * 62)
    for member, entry in zip(panel, panel_draw_choices(panel, game)):
        agrees = entry["choice"] == user_choice
        member.draw_agreements += agrees
        marker = "=" if agrees else "≠"
        print(f"  [{marker}] {member.name:<16} {entry['reasoning']}")


def reveal_discard_choices(
    panel: list[PanelMember], game: Game, user_card: Card
) -> None:
    print(f"\nYou discarded: {user_card}")
    print("-" * 62)
    for member, entry in zip(panel, panel_discard_choices(panel, game)):
        agrees = entry["card"] == user_card
        member.discard_agreements += agrees
        marker = "=" if agrees else "≠"
        print(f"  [{marker}] {member.name:<16} {entry['reasoning']}")
        if entry["mc_candidates"]:
            top3 = entry["mc_candidates"][:3]
            evs = ", ".join(f"{c['card']}: {c['avg_points']:+.1f}" for c in top3)
            print(f"        MC EVs (top 3): {evs}")


def reveal_knock_choices(
    panel: list[PanelMember],
    game: Game,
    post_hand: Hand,
    pending: Card,
    user_knocks: bool,
) -> None:
    print(f"\nYou chose: {'KNOCK' if user_knocks else 'keep playing'}")
    print("-" * 62)
    for member, entry in zip(panel, panel_knock_choices(panel, game, post_hand, pending)):
        agrees = entry["knocks"] == user_knocks
        member.knock_agreements += agrees
        marker = "=" if agrees else "≠"
        print(f"  [{marker}] {member.name:<16} {entry['reasoning']}")


def reset_panel_tracking(panel: list[PanelMember]) -> None:
    """Clear per-hand opponent tracking on every panel member that has it."""
    for member in panel:
        if member.is_context_aware:
            member.ai.reset_for_new_hand()


def run_scenario(seed: int, panel: list[PanelMember]) -> bool:
    """Run one scenario. Returns False if generation failed for this seed."""
    for attempt in range(MAX_GENERATION_ATTEMPTS):
        # Each attempt plays a fresh hand, so the panel must forget what it
        # saw during a failed attempt (the callbacks feed it opponent actions).
        reset_panel_tracking(panel)
        game = generate_scenario(seed + attempt * 1000, panel)
        if game is not None:
            break
    else:
        return False

    show_position(game)

    # --- Decision 1: draw ---
    user_draw = ask_draw(game)
    reveal_draw_choices(panel, game, user_draw)

    if user_draw == DrawChoice.DISCARD:
        drawn = game.draw_from_discard()
    else:
        drawn = game.draw_from_deck()
    print(f"\nYou drew: {drawn}")

    # --- Decision 2: discard ---
    user_discard = ask_discard(game)
    reveal_discard_choices(panel, game, user_discard)

    # --- Decision 3: knock (only if eligible) ---
    human = game.players[HUMAN_SEAT]
    post_deadwood = calculate_post_discard_deadwood(human.hand, user_discard)
    if post_deadwood <= game.knock_threshold:
        answer = ask(
            f"\nDiscarding {user_discard} leaves {post_deadwood} deadwood. Knock? [y/n] ",
            {"y", "n"},
        )
        post_hand = Hand([c for c in human.hand if c != user_discard])
        reveal_knock_choices(panel, game, post_hand, user_discard, answer == "y")

    return True


def print_summary(panel: list[PanelMember], scenarios: int) -> None:
    print("\n" + "=" * 62)
    print(f"SESSION SUMMARY ({scenarios} scenario{'s' if scenarios != 1 else ''})")
    print("=" * 62)
    print(f"{'AI':<18} {'draw':>6} {'discard':>9} {'knock':>7}")
    for member in panel:
        print(
            f"{member.name:<18} {member.draw_agreements:>6} "
            f"{member.discard_agreements:>9} {member.knock_agreements:>7}"
        )
    print("\n(counts = times the AI agreed with your choice)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Quiz yourself against the AIs on random gin rummy scenarios"
    )
    parser.add_argument("--count", type=int, default=3, help="Number of scenarios")
    parser.add_argument("--seed", type=int, default=None, help="Base RNG seed")
    parser.add_argument("--mc-sims", type=int, default=500,
                        help="MC simulations per decision (default 500: ~2-4s per answer)")
    parser.add_argument("--mc-workers", type=int, default=8,
                        help="MC worker processes (8 saturates the useful parallelism)")
    args = parser.parse_args()

    base_seed = args.seed if args.seed is not None else random.randrange(1_000_000)
    print(f"Gin Rummy scenario quiz (seed {base_seed}, q to quit at any prompt)")

    panel = build_panel(args.mc_sims, args.mc_workers)
    completed = 0
    for i in range(args.count):
        # run_scenario resets opponent tracking per attempt; tallies persist
        if run_scenario(base_seed + i, panel):
            completed += 1
        else:
            print(f"\n(scenario {i + 1}: could not generate a stable position, skipped)")

    if completed:
        print_summary(panel, completed)

    for member in panel:
        if isinstance(member.ai, MonteCarloAI):
            member.ai.shutdown()


if __name__ == "__main__":
    main()
